# The service providing the commit statuses to GitHub.
status = ["buildbot/buildbot-build-script"]

# Allow 3 hours for builds + tests.
timeout_sec = 10800

# Have bors delete auto-merged branches
delete_merged_branches = true

cut_body_after = ""
