# The service providing the commit statuses to GitHub.
status = [
  "buildbot/ykrustc-buildbot-build-script-hwt",
  "buildbot/ykrustc-buildbot-build-script-swt",
]

# Allow eight hours for builds + tests.
timeout_sec = 28800

# Have bors delete auto-merged branches
delete_merged_branches = true
