[package]
name = "yktrace"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
byteorder = "1.4.3"
elf = "0.0.10"
fxhash = "0.2.1"
gimli = "0.24.0"
hwtracer = { git = "https://github.com/softdevteam/hwtracer" }
intervaltree = "0.2.6"
leb128 = "0.2.4"
libc = "0.2.97"
memmap2 = "0.3.0"
once_cell = "1.8.0"
phdrs = { git = "https://github.com/softdevteam/phdrs" }
ykllvmwrap = { path = "../ykllvmwrap" }
ykutil = { path = "../ykutil" }

[dependencies.object]
version = "0.25.3"
default-features = false
features = ["read_core", "elf"]

[dev-dependencies]
fm = "0.2.1"
regex = "1.5.4"

[features]
c_testing = []
