[package]
name = "yksgi"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = "0.2.97"
ykutil = { path = "../ykutil" }
llvm-sys = "130"

[features]
c_testing = []
